INSERT INTO properties (
    active,
    city,
    cost_per_night,
    country,
    cover_photo_url,
    description,
    number_of_bathrooms,
    number_of_bedrooms,
    owner_id,
    parking_spaces,
    post_code,
    province,
    street,
    thumbnail_photo_url,
    title
  )
VALUES
  (
    true,
    'Vancouver',
    50,
    'Canada',
    'https://images.pixels.com/photos/1234567',
    'description:text',
    3,
    4,
    3,
    2,
    '12345',
    'British Columbia',
    '401 W Georgia Street',
    'https://images.pixels.com/photos/7483756',
    'Fun Red'
  ),
  (
    true,
    'Vancouver',
    40,
    'Canada',
    'https://images.pixels.com/photos/0384766',
    'description:text',
    5,
    6,
    2,
    8,
    '19335',
    'British Columbia',
    '420 W Georgia Street',
    'https://images.pixels.com/photos/0293746',
    'Fun Yellow'
  ),
  (
    true,
    'Vancouver',
    40,
    'Canada',
    'https://images.pixels.com/photos/0384766',
    'description:text',
    5,
    6,
    2,
    8,
    '19335',
    'British Columbia',
    '420 W Georgia Street',
    'https://images.pixels.com/photos/0293746',
    'Fun Yellow'
  ),
  (
    true,
    'Vancouver',
    43,
    'Canada',
    'https://images.pixels.com/photos/0444766',
    'description:text',
    4,
    4,
    4,
    4,
    '19445',
    'British Columbia',
    '444 W Georgia Street',
    'https://images.pixels.com/photos/0244446',
    'Fun Yel444'
  ),
  (
    true,
    'Vancouver',
    55,
    'Canada',
    'https://images.pixels.com/photos/0444556',
    'description:text',
    5,
    5,
    4,
    4,
    '15545',
    'British Columbia',
    '544 W Georgia Street',
    'https://images.pixels.com/photos/0244556',
    'Fun Ye55544'
  ),
  (
    true,
    'Vancouver',
    66,
    'Canada',
    'https://images.pixels.com/photos/6644766',
    'description:text',
    6,
    4,
    8,
    6,
    '66445',
    'British Columbia',
    '464 W Georgia Street',
    'https://images.pixels.com/photos/0664446',
    'Fun Ye644'
  ),
  (
    true,
    'Vancouver',
    73,
    'Canada',
    'https://images.pixels.com/photos/0744766',
    'description:text',
    5,
    4,
    7,
    4,
    '17745',
    'British Columbia',
    '444 W Georgia Street',
    'https://images.pixels.com/photos/0774446',
    'Fun Yel4474'
  ),
  (
    true,
    'Vancouver',
    48,
    'Canada',
    'https://images.pixels.com/photos/0484766',
    'description:text',
    4,
    1,
    9,
    3,
    '18445',
    'British Columbia',
    '488 W Georgia Street',
    'https://images.pixels.com/photos/0884446',
    'Fun Ye844'
  );